# Generated by Django 5.2.17 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
